---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taiko-nethermind.fullname" . }}-scripts
  labels:
    {{- include "taiko-nethermind.labels" . | nindent 4 }}
data:
  init.sh: |
    #!/bin/sh

    echo "Namespace: ${POD_NAMESPACE} Pod: ${POD_NAME}";
    echo "Starting init script for pod ${POD_NAME}..."
    touch /shared/env

    echo "Getting node external ip..."
    EXTERNAL_NODE_IP=$(kubectl get nodes "${NODE_NAME}" -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}');
    echo "Getting execution node port..."
    EXTERNAL_NODE_PORT=$(kubectl get services -l "pod=${POD_NAME},client=taiko-nethermind,type=p2p" -o jsonpath='{.items[0].spec.ports[0].nodePort}')

    echo "EXTERNAL_NODE_IP=${EXTERNAL_NODE_IP}"
    echo "EXTERNAL_NODE_PORT=${EXTERNAL_NODE_PORT}"

    echo "export EXTERNAL_NODE_IP=${EXTERNAL_NODE_IP}" >> /shared/env
    echo "export EXTERNAL_NODE_PORT=${EXTERNAL_NODE_PORT}" >> /shared/env

    {{- if .Values.global.secret.jwt }}
    echo "{{ .Values.global.secret.jwt }}" >> /shared/jwtsecret
    {{- end }}
    exit 0
