{{- range $i := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiko-nethermind.fullname" $ }}-p2p-{{ $i }}
  labels:
    type: p2p
    client: taiko-nethermind
    pod: {{ include "taiko-nethermind.fullname" $ }}-{{ $i }}
    {{- include "taiko-nethermind.labels" $ | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ $.Values.service.ports.p2p }}
      targetPort: exec-p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ $.Values.service.ports.p2p }}
      targetPort: exec-p2p-udp
      protocol: UDP
      name: p2p-udp
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "taiko-nethermind.fullname" $ }}-{{ $i }}
    {{- include "taiko-nethermind.selectorLabels" $ | nindent 4 }}
{{- end }}
