---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiko-nethermind.fullname" . }}
  labels:
    {{- include "taiko-nethermind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: exec-http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.ws }}
      targetPort: exec-ws
      protocol: TCP
      name: ws
    - port: {{ .Values.service.ports.authrpc }}
      targetPort: exec-authrpc
      protocol: TCP
      name: authrpc
    - port: {{ .Values.service.ports.metrics }}
      targetPort: exec-metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "taiko-nethermind.selectorLabels" . | nindent 4 }}
