{{- if and (eq .Values.global.mode "proposer") .Values.global.secret.createProposerPrivateKey }}  
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiko-client.fullname" . }}-proposer-private-key
type: Opaque
data:
  default: {{ index .Values.global.secret.privateKeys "proposer" | b64enc }}
{{- end }}
{{- if and (eq .Values.global.mode "prover") .Values.global.secret.createProverPrivateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiko-client.fullname" . }}-prover-private-key
type: Opaque
data:
  default: {{ index .Values.global.secret.privateKeys "prover" | b64enc }}
{{- end }}
{{- if and (eq .Values.global.mode "guardian") .Values.global.secret.createGuardianPrivateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiko-client.fullname" . }}-guardian-private-key
type: Opaque
data:
  default: {{ index .Values.global.secret.privateKeys "guardian" | b64enc }}
{{- end }}
