name: Helm Charts Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  helm-chart-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Helm Dependencies
        run: |
          for dir in charts/*; do
            helm dependency update "$dir";
          done
      #     helm repo add bitnami https://charts.bitnami.com/bitnami
      #     helm repo add ethereum-helm-charts https://ethpandaops.github.io/ethereum-helm-charts
      #     helm repo add prometheus-charts https://prometheus-community.github.io/helm-charts
      #     helm repo add grafana https://grafana.github.io/helm-charts
      #     helm repo add external-secrets https://charts.external-secrets.io

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_SKIP_EXISTING: true
          CR_GENERATE_RELEASE_NOTES: true
